### ISSUE TITLE
controller 多副本情况下，选主问题

### ISSUE THREAD

**Issue by ii2day** [kdoctor-io/kdoctor#164]
多副本存在多个 lease 情况，
需要验证是否有问题，目前来看任务执行没有问题，报告收取可能存在问题

**Comment by weizhoublue** [comment]
是否 有 结论

**Comment by ii2day** [comment]
选主存在问题，存在多个 lease 没有 主从切换

> 是否 有 结论

https://github.com/kdoctor-io/kdoctor/issues/164#issuecomment-1698450419

**Comment by ii2day** [comment]
done
