### ISSUE TITLE
Failed to get the dns service IP list

### ISSUE THREAD

**Issue by carryaimp** [kdoctor-io/kdoctor#303]
**kdocker agent app v0.2.0**

**Failed to get the dns service IP list**
![image](https://github.com/kdoctor-io/kdoctor/assets/26008241/d050c0fb-00ef-4c3d-af3f-5863abd67e91)

**Hwo To Reproduce**
In the program, the default dns service label is selected as "k8s-app": "kube-dns". In the official definition of core-dns, this label is not available, resulting in an empty IP list corresponding to the acquisition of DNS services, resulting in a subsequent index error on the list:Panic details: runtime error: index out of range [0] with length 0

The default core-dns service name is :kubernetes.io/name: "CoreDNS", official link: https://github.com/coredns/helm/blob/master/charts/coredns/templates/_helpers.tpl

**Expected behavior**
Correct DNS service IP address list

**Comment by ii2day** [comment]
@carryaimp  Thank you for raising this issue. The kube-dns label does look a bit old. You are welcome to submit a PR to fix this issue.
