### ISSUE TITLE
kdoctor-agent keep ContainerCreating

### ISSUE THREAD

**Issue by xinmans** [kdoctor-io/kdoctor#326]
1.  Install steps: 

  _helm repo add kdoctor https://kdoctor-io.github.io/kdoctor
  helm repo update kdoctor
  helm install kdoctor kdoctor/kdoctor     -n kdoctor --debug --create-namespace_ 

2. Check status

 kubectl get pod -n kdoctor

  Normal   Scheduled    4m52s  default-scheduler  Successfully assigned kdoctor/kdoctor-agent-gs9t4 to k6sworker-1
  Warning  FailedMount  4m51s  kubelet            MountVolume.SetUp failed for volume "config-path" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulling      4m50s  kubelet            Pulling image "ghcr.io/kdoctor-io/kdoctor-agent:v0.2.0"

**Comment by ii2day** [comment]
@xinmans Use the `kubectl get configmap -n kdoctor` command to see if you can see the two configmaps kdocotr and kdoctor-app-config-template

**Comment by weizhoublue** [comment]
is it pending for pulling image ghcr.io/kdoctor-io/kdoctor-agent:v0.2.0 ? 

are you a china user and not able to access ghcr.io ? you could set helm option ' --set global. imageRegistryOverride=ghcr.m.daocloud.io '  to pull image from image registry in china

**Comment by ii2day** [comment]
@xinmans Is the problem solved?

**Comment by xinmans** [comment]
Yes, solved, thanks

**Comment by ty-dc** [comment]
close.
