### ISSUE TITLE
"IPv6": not configured on this cluster

### ISSUE THREAD

**Issue by xphsc** [kdoctor-io/kdoctor#504]
![image](https://github.com/kdoctor-io/kdoctor/assets/29444520/c286c5e9-e38b-4a9d-bcd0-94bd0c355433)

**Comment by ii2day** [comment]
The default installation of kdoctor is dual-stack. To use kdoctor with a single-stack ipv4 cluster, install kdoctor with --set feature.enableIPv6=false.

**Comment by xphsc** [comment]
ok

**Comment by ii2day** [comment]
> ok

Looking forward to your contributions to kdoctor
