### ISSUE TITLE
software bug

### ISSUE THREAD

**Issue by light2cloud** [kdoctor-io/kdoctor#506]
**Describe the version**
apiVersion: v2
appVersion: 0.2.2
description: kdoctor

**Describe the bug**
 kdoctor-controller pod
After deployment, the pods are functioning normally, but the logs continue to output：

E0223 09:29:29.681292       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"watch API not implement"}: watch API not implement

**Comment by ii2day** [comment]
@light2cloud  This log error for aggregation api watch interface is not implemented, the current do not watch function, this log output will be followed up, optimize it, does not affect the normal use.

**Comment by light2cloud** [comment]
OK，thanks
