### ISSUE TITLE
DNS server instability in unit tests causes failures

### ISSUE THREAD

**Issue by weizhoublue** [kdoctor-io/kdoctor#69]
action url: https://github.com/kdoctor-io/kdoctor/actions/runs/5479687487

**Comment by ii2day** [comment]
由于 server 的异常返回导致用例失败。

**Comment by weizhoublue** [comment]
如何 改进 ？

**Comment by ii2day** [comment]
> 

mock server 的返回 或者 换一个 稳定的 dns server 现在用的 server 是 daocloud 的

**Comment by ii2day** [comment]
> 如何 改进 ？

mock server 的返回 或者 换一个 稳定的 dns server 现在用的 server 是 daocloud 的
